version: "3"
services:
  inspectra-admin-test:
    container_name: inspectra-admin-test
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: lyhou123/inspectra-admin:latest
    ports:
      - "4013:3000"
    environment:
      - NODE_ENV=production
      - GENERATE_SOURCEMAP=false
