version: '3'
services:
  inspectra-admin-test:
    container_name: inspectra-admin-test
    image: lyhou123/admin:latest
    restart: always
    ports:
      - "4016:3000"
    environment:
      - NODE_ENV=production
      - GENERATE_SOURCEMAP=false
