'use client'

import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/sidebar/app-sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import { UserNav } from "@/components/navbar";
import {useEffect, useState} from "react";
import StoreProvider from "./StoreProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);  // Set to true once mounted
  }, []);

  if (!mounted) {
    return null;  // Return null until the component is mounted
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
      <StoreProvider>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <AppSidebar />
            <main className="w-full">
              <SidebarTrigger />
              <UserNav />
              {children}
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </StoreProvider>
      </body>
    </html>
  );
}
